### ISSUE TITLE
pipe vertices missing using bokehplot()

### ISSUE THREAD

**Issue by jermaine1ronquillo** [oopnet/oopnet#36]
## Checks
- [x] I added a descriptive title to this issue
- [x] I have searched (Google, GitHub) for similar issues and couldn't find anything
- [x] I have read and followed the docs and still think this is a bug

# Bug Description
vertices missing using bokehplot()

# Steps to Reproduce
output_file('bokehexample.html')
plot = network2.bokehplot(nodes=p, links=f, colormap=dict(node='viridis', link='cool'))
show(plot)
# Expected Behavior
vertices should be reflected (same output of plot())

# Screenshots
![bokeh_plot](https://user-images.githubusercontent.com/15191328/187120771-25c6e879-f793-4a2b-8dfb-9aab4ae04a3a.png)

# Additional context

**Comment by tiuri101** [comment]
Thank you for the issue! I pushed a new version that should fix this, meaning that matplotlib and bokeh should both plot pipe vertices. While fixing this, I saw that vertices are not plotted for pumps or valves but I'll create a new issue for this.

**Comment by tiuri101** [comment]
Created the new issue, closing this one.
